#!/bin/bash

# Run only the zsh-history-bind test
echo "Running zsh-history-bind feature test..."
devcontainer features test --features zsh-history-bind --global-scenarios-only=false --skip-autogenerated=false ./
