#!/bin/bash

# Run only the zsh-history-volume test
echo "Running zsh-history-volume feature test..."
devcontainer features test --features zsh-history-volume --global-scenarios-only=false --skip-autogenerated=false ./
